//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace spring.net_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class 仪器设备表
    {
        public string 仪器名称 { get; set; }
        public string 仪器编号 { get; set; }
        public string 型号规格 { get; set; }
        public Nullable<System.DateTime> 校准日期 { get; set; }
        public Nullable<System.DateTime> 有效期至 { get; set; }
        public string 精度等级 { get; set; }
        public string 制造厂商 { get; set; }
        public string 出厂日期 { get; set; }
        public string 检定单位 { get; set; }
        public string 出厂编号 { get; set; }
        public string 检定证书号 { get; set; }
        public string 计量检定情况 { get; set; }
        public Nullable<decimal> 检定单价 { get; set; }
        public string 机器号 { get; set; }
        public bool 停用 { get; set; }
        public string 使用科室 { get; set; }
        public int 编号 { get; set; }
        public string 保管人 { get; set; }
        public string 检定周期 { get; set; }
        public string 包含仪器 { get; set; }
        public string 备注 { get; set; }
        public Nullable<decimal> 价格 { get; set; }
        public string 启用时间 { get; set; }
    }
}
